version: "3.9"
    services:
      backend:
        build: ./Backend
        ports:
          - "8080:8080"
        volumes:
          - ./Backend:/app
      frontend:
        build: ./Frontend
        ports:
          - "80:80"
        volumes:
          - ./Frontend:/app
      nginx:
        image: nginx:alpine
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
          - ./certs:/etc/ssl/certs 
        depends_on:
          - backend